import numpy as np
from pathlib import Path

from viewser import Queryset, Column

def get_data():
    """
    Retrieves conflict history data from the Views-escwa database at the country_month level.

    Returns:
    - data (pd.DataFrame): DataFrame containing conflict history data.

    Raises:
    - ValueError: If there is an issue with fetching or processing the data.

    Notes:
    - The function queries the 'escwa001_cflong' table from the Views-escwa database at the country_month level.
    - It includes various transformations and calculations for target variables, temporal lags, decay functions,
      spatial lag decay functions, and more.
    - The resulting DataFrame is saved as a Parquet file in the 'data/raw' directory.
    """
    print("Getting data...")
    qs_cm_cflong  = (Queryset("escwa001_cflong", "country_month")
                # target variable
                .with_column(Column("ged_sb_dep", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            )
                # timelag 0 of target variable
                .with_column(Column("ged_sb_dummy_t0", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            )
                # further timelags of target variable
                # sb
                .with_column(Column("ged_sb_dummy_t1", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_sb_dummy_t2", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(2)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_sb_dummy_t3", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(3)
                            .transform.missing.fill()
                            ) 
                .with_column(Column("ged_sb_dummy_t4", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(4)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_sb_dummy_t5", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(5)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_sb_dummy_t6", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(6)
                            .transform.missing.fill()
                            )
                        
                # os
                .with_column(Column("ged_os_dummy_t0", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_os_dummy_t1", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_os_dummy_t2", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(2)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_os_dummy_t3", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(3)
                            .transform.missing.fill()
                            )                    
                .with_column(Column("ged_os_dummy_t4", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(4)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_os_dummy_t5", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(5)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_os_dummy_t6", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(6)
                            .transform.missing.fill()
                            )
                # ns
                .with_column(Column("ged_ns_dummy_t0", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_ns_dummy_t1", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_ns_dummy_t2", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(2)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_ns_dummy_t3", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(3)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_ns_dummy_t4", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(4)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_ns_dummy_t5", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(5)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_ns_dummy_t6", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(6)
                            .transform.missing.fill()
                            )
                # Decay functions
                # sb
                .with_column(Column("decay_ged_sb_1", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(1)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_sb_5", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(5)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_sb_25", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(25)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_sb_100", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(100)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_sb_500", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(500)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                # os
                
                .with_column(Column("decay_ged_os_1", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(1)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_os_5", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(5)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_os_25", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(25)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_os_100", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(100)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )         
                        
                # ns
                .with_column(Column("decay_ged_ns_1", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(1)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_ns_5", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(5)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_ns_25", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(25)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_ns_100", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(100)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                        
                # Spatial lag decay functions
                        # sb
                .with_column(Column("splag_1_decay_ged_sb_25", from_table="ged2_cm",
                                    from_column="ged_sb_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(25)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.spatial.countrylag(1, 1, 0, 0)
                            .transform.missing.replace_na()
                            )

                .with_column(Column("splag_1_decay_ged_sb_500", from_table="ged2_cm",
                                    from_column="ged_sb_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(500)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.spatial.countrylag(1, 1, 0, 0)
                            .transform.missing.replace_na()
                            )
                # os
                .with_column(Column("splag_1_decay_ged_os_25", from_table="ged2_cm",
                                    from_column="ged_os_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(25)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.spatial.countrylag(1, 1, 0, 0)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("splag_1_decay_ged_os_500", from_table="ged2_cm",
                                    from_column="ged_os_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(500)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.spatial.countrylag(1, 1, 0, 0)
                            .transform.missing.replace_na()
                            )
                # ns
                .with_column(Column("splag_1_decay_ged_ns_25", from_table="ged2_cm",
                                    from_column="ged_ns_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(25)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.spatial.countrylag(1, 1, 0, 0)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("splag_1_decay_ged_ns_500", from_table="ged2_cm",
                                    from_column="ged_ns_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(500)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.spatial.countrylag(1, 1, 0, 0)
                            .transform.missing.replace_na()
                            )
            
                .with_theme("views-escwa")
                .describe("""Views-escwa conflict history, cm level


                            """)
                )
    #data = qs_cm_cflong.publish().fetch()
    data = qs_cm_cflong.fetch()
    data = data.astype(float) # Recast all columns to float because of an excessive assert in the stepshift library
    data.to_parquet(f"{Path(__file__).parent.parent.parent}/data/raw/raw_calibration.parquet") #wd is this model/src/dataloaders
    
    print("Data fetched and saved in data/raw!")
    
    return data
    

if __name__ == "__main__":

    # Call the function
    get_data()