wandb_version: 1

learning_rate:
  desc: null
  value: 0.05
n_estimators:
  desc: null
  value: 100
n_jobs:
  desc: null
  value: 12
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.0
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709041431.814503
    t:
      1:
      - 5
      - 8
      - 53
      - 55
      - 105
      2:
      - 5
      - 8
      - 53
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.16.0
      8:
      - 4
      - 5
      13: darwin-arm64
