from viewser import Queryset, Column

def generate():
    """
    Contains the configuration for the input data in the form of a viewser queryset. That is the data from viewser that is used to train the model.
    This configuration is "behavioral" so modifying it will affect the model's runtime behavior and integration into the deployment system.
    There is no guarantee that the model will work if the input data configuration is changed here without changing the model settings and algorithm accordingly.

    Returns:
    - queryset_base (Queryset): A queryset containing the base data for the model training.
    """
    
    # VIEWSER 6, Example configuration. Modify as needed.

    queryset_base = (Queryset('fatalities002_all_features','country_month')
    .with_column(Column('gleditsch_ward', from_loa='country', from_column='gwcode')
        )

    .with_column(Column('ln_ged_sb_dep', from_loa='country_month', from_column='ged_sb_best_sum_nokgi')
        .transform.ops.ln()
        .transform.missing.fill()
        )

    .with_column(Column('ln_ged_sb', from_loa='country_month', from_column='ged_sb_best_sum_nokgi')
        .transform.ops.ln()
        .transform.missing.fill()
        )

    .with_column(Column('ln_ged_ns', from_loa='country_month', from_column='ged_ns_best_sum_nokgi')
        .transform.ops.ln()
        .transform.missing.fill()
        )

    .with_column(Column('ln_ged_os', from_loa='country_month', from_column='ged_os_best_sum_nokgi')
        .transform.ops.ln()
        .transform.missing.fill()
        )

    .with_column(Column('ln_acled_sb', from_loa='country_month', from_column='acled_sb_fat')
        .transform.ops.ln()
        .transform.missing.fill()
        )

    .with_column(Column('ln_acled_sb_count', from_loa='country_month', from_column='acled_sb_count')
        .transform.ops.ln()
        .transform.missing.fill()
        )

    .with_column(Column('ln_acled_os', from_loa='country_month', from_column='acled_os_fat')
        .transform.ops.ln()
        .transform.missing.fill()
        )

    .with_column(Column('wdi_ag_lnd_frst_k2', from_loa='country_year', from_column='wdi_ag_lnd_frst_k2')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_dt_oda_odat_pc_zs', from_loa='country_year', from_column='wdi_dt_oda_odat_pc_zs')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_ms_mil_xpnd_gd_zs', from_loa='country_year', from_column='wdi_ms_mil_xpnd_gd_zs')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_ms_mil_xpnd_zs', from_loa='country_year', from_column='wdi_ms_mil_xpnd_zs')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_nv_agr_totl_kd', from_loa='country_year', from_column='wdi_nv_agr_totl_kd')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_nv_agr_totl_kn', from_loa='country_year', from_column='wdi_nv_agr_totl_kn')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_ny_gdp_pcap_kd', from_loa='country_year', from_column='wdi_ny_gdp_pcap_kd')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_sp_dyn_le00_in', from_loa='country_year', from_column='wdi_sp_dyn_le00_in')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_se_enr_prim_fm_zs', from_loa='country_year', from_column='wdi_se_enr_prim_fm_zs')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_se_enr_prsc_fm_zs', from_loa='country_year', from_column='wdi_se_enr_prsc_fm_zs')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_se_prm_nenr', from_loa='country_year', from_column='wdi_se_prm_nenr')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_sh_sta_maln_zs', from_loa='country_year', from_column='wdi_sh_sta_maln_zs')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_sh_sta_stnt_zs', from_loa='country_year', from_column='wdi_sh_sta_stnt_zs')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_sl_tlf_totl_fe_zs', from_loa='country_year', from_column='wdi_sl_tlf_totl_fe_zs')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_sm_pop_refg_or', from_loa='country_year', from_column='wdi_sm_pop_refg_or')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_sm_pop_netm', from_loa='country_year', from_column='wdi_sm_pop_netm')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_sm_pop_totl_zs', from_loa='country_year', from_column='wdi_sm_pop_totl_zs')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_sp_dyn_imrt_in', from_loa='country_year', from_column='wdi_sp_dyn_imrt_in')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_sh_dyn_mort_fe', from_loa='country_year', from_column='wdi_sh_dyn_mort_fe')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_sp_pop_14_fe_zs', from_loa='country_year', from_column='wdi_sp_pop_0014_fe_zs')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_sp_pop_1564_fe_zs', from_loa='country_year', from_column='wdi_sp_pop_1564_fe_zs')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_sp_pop_65up_fe_zs', from_loa='country_year', from_column='wdi_sp_pop_65up_fe_zs')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_sp_pop_grow', from_loa='country_year', from_column='wdi_sp_pop_grow')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_sp_urb_totl_in_zs', from_loa='country_year', from_column='wdi_sp_urb_totl_in_zs')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_delibdem', from_loa='country_year', from_column='vdem_v2x_delibdem')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_egaldem', from_loa='country_year', from_column='vdem_v2x_egaldem')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_libdem', from_loa='country_year', from_column='vdem_v2x_libdem')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_libdem_48', from_loa='country_year', from_column='vdem_v2x_libdem')
        .transform.missing.fill()
        .transform.temporal.tlag(60)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_partip', from_loa='country_year', from_column='vdem_v2x_partip')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_partipdem', from_loa='country_year', from_column='vdem_v2x_partipdem')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_accountability', from_loa='country_year', from_column='vdem_v2x_accountability')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_civlib', from_loa='country_year', from_column='vdem_v2x_civlib')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_clphy', from_loa='country_year', from_column='vdem_v2x_clphy')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_cspart', from_loa='country_year', from_column='vdem_v2x_cspart')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_divparctrl', from_loa='country_year', from_column='vdem_v2x_divparctrl')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_edcomp_thick', from_loa='country_year', from_column='vdem_v2x_edcomp_thick')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_egal', from_loa='country_year', from_column='vdem_v2x_egal')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_execorr', from_loa='country_year', from_column='vdem_v2x_execorr')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_frassoc_thick', from_loa='country_year', from_column='vdem_v2x_frassoc_thick')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_gencs', from_loa='country_year', from_column='vdem_v2x_gencs')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_gender', from_loa='country_year', from_column='vdem_v2x_gender')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_genpp', from_loa='country_year', from_column='vdem_v2x_genpp')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_horacc', from_loa='country_year', from_column='vdem_v2x_horacc')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_neopat', from_loa='country_year', from_column='vdem_v2x_neopat')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_pubcorr', from_loa='country_year', from_column='vdem_v2x_pubcorr')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_rule', from_loa='country_year', from_column='vdem_v2x_rule')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_veracc', from_loa='country_year', from_column='vdem_v2x_veracc')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_ex_military', from_loa='country_year', from_column='vdem_v2x_ex_military')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_ex_party', from_loa='country_year', from_column='vdem_v2x_ex_party')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_freexp', from_loa='country_year', from_column='vdem_v2x_freexp')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xcl_acjst', from_loa='country_year', from_column='vdem_v2xcl_acjst')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xcl_dmove', from_loa='country_year', from_column='vdem_v2xcl_dmove')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xcl_prpty', from_loa='country_year', from_column='vdem_v2xcl_prpty')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xcl_rol', from_loa='country_year', from_column='vdem_v2xcl_rol')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xcl_slave', from_loa='country_year', from_column='vdem_v2xcl_slave')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xdd_dd', from_loa='country_year', from_column='vdem_v2xdd_dd')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xdl_delib', from_loa='country_year', from_column='vdem_v2xdl_delib')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xeg_eqdr', from_loa='country_year', from_column='vdem_v2xeg_eqdr')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xeg_eqprotec', from_loa='country_year', from_column='vdem_v2xeg_eqprotec')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xel_frefair', from_loa='country_year', from_column='vdem_v2xel_frefair')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xel_regelec', from_loa='country_year', from_column='vdem_v2xel_regelec')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xme_altinf', from_loa='country_year', from_column='vdem_v2xme_altinf')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xnp_client', from_loa='country_year', from_column='vdem_v2xnp_client')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xnp_regcorr', from_loa='country_year', from_column='vdem_v2xnp_regcorr')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xpe_exlecon', from_loa='country_year', from_column='vdem_v2xpe_exlecon')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xpe_exlpol', from_loa='country_year', from_column='vdem_v2xpe_exlpol')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xpe_exlgeo', from_loa='country_year', from_column='vdem_v2xpe_exlgeo')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xpe_exlgender', from_loa='country_year', from_column='vdem_v2xpe_exlgender')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xpe_exlsocgr', from_loa='country_year', from_column='vdem_v2xpe_exlsocgr')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xps_party', from_loa='country_year', from_column='vdem_v2xps_party')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xcs_ccsi', from_loa='country_year', from_column='vdem_v2xcs_ccsi')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xnp_pres', from_loa='country_year', from_column='vdem_v2xnp_pres')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2xeg_eqaccess', from_loa='country_year', from_column='vdem_v2xeg_eqaccess')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2x_diagacc', from_loa='country_year', from_column='vdem_v2x_diagacc')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('vdem_v2clrgunev', from_loa='country_year', from_column='vdem_v2clrgunev')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        )

    .with_column(Column('wdi_sp_pop_totl', from_loa='country_year', from_column='wdi_sp_pop_totl')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.missing.fill()
        .transform.missing.replace_na()
        )

    .with_column(Column('ln_ged_sb_tlag_1', from_loa='country_month', from_column='ged_sb_best_sum_nokgi')
        .transform.ops.ln()
        .transform.missing.fill()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('ln_ged_sb_tlag_2', from_loa='country_month', from_column='ged_sb_best_sum_nokgi')
        .transform.ops.ln()
        .transform.missing.fill()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('ln_ged_sb_tlag_3', from_loa='country_month', from_column='ged_sb_best_sum_nokgi')
        .transform.ops.ln()
        .transform.missing.fill()
        .transform.temporal.tlag(3)
        .transform.missing.fill()
        )

    .with_column(Column('ln_ged_sb_tlag_4', from_loa='country_month', from_column='ged_sb_best_sum_nokgi')
        .transform.ops.ln()
        .transform.missing.fill()
        .transform.temporal.tlag(4)
        .transform.missing.fill()
        )

    .with_column(Column('ln_ged_sb_tlag_5', from_loa='country_month', from_column='ged_sb_best_sum_nokgi')
        .transform.ops.ln()
        .transform.missing.fill()
        .transform.temporal.tlag(5)
        .transform.missing.fill()
        )

    .with_column(Column('ln_ged_sb_tlag_6', from_loa='country_month', from_column='ged_sb_best_sum_nokgi')
        .transform.ops.ln()
        .transform.missing.fill()
        .transform.temporal.tlag(6)
        .transform.missing.fill()
        )

    .with_column(Column('ln_ged_sb_tsum_24', from_loa='country_month', from_column='ged_sb_best_sum_nokgi')
        .transform.missing.replace_na()
        .transform.temporal.moving_sum(24)
        .transform.ops.ln()
        .transform.missing.replace_na()
        )

    .with_column(Column('ln_ged_os_tlag_1', from_loa='country_month', from_column='ged_os_best_sum_nokgi')
        .transform.ops.ln()
        .transform.missing.fill()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_tokens_t1', from_loa='country_month', from_column='topic_tokens')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_tokens_t2', from_loa='country_month', from_column='topic_tokens')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('topic_tokens_t13', from_loa='country_month', from_column='topic_tokens')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta0_stock_t1', from_loa='country_month', from_column='topic_ste_theta0_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta0_stock_t2', from_loa='country_month', from_column='topic_ste_theta0_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta0_stock_t13', from_loa='country_month', from_column='topic_ste_theta0_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta1_stock_t1', from_loa='country_month', from_column='topic_ste_theta1_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta1_stock_t2', from_loa='country_month', from_column='topic_ste_theta1_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta1_stock_t13', from_loa='country_month', from_column='topic_ste_theta1_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta2_stock_t1', from_loa='country_month', from_column='topic_ste_theta2_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta2_stock_t2', from_loa='country_month', from_column='topic_ste_theta2_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta2_stock_t13', from_loa='country_month', from_column='topic_ste_theta2_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta3_stock_t1', from_loa='country_month', from_column='topic_ste_theta3_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta3_stock_t2', from_loa='country_month', from_column='topic_ste_theta3_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta3_stock_t13', from_loa='country_month', from_column='topic_ste_theta3_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta4_stock_t1', from_loa='country_month', from_column='topic_ste_theta4_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta4_stock_t2', from_loa='country_month', from_column='topic_ste_theta4_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta4_stock_t13', from_loa='country_month', from_column='topic_ste_theta4_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta5_stock_t1', from_loa='country_month', from_column='topic_ste_theta5_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta5_stock_t2', from_loa='country_month', from_column='topic_ste_theta5_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta5_stock_t13', from_loa='country_month', from_column='topic_ste_theta5_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta6_stock_t1', from_loa='country_month', from_column='topic_ste_theta6_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta6_stock_t2', from_loa='country_month', from_column='topic_ste_theta6_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta6_stock_t13', from_loa='country_month', from_column='topic_ste_theta6_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta7_stock_t1', from_loa='country_month', from_column='topic_ste_theta7_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta7_stock_t2', from_loa='country_month', from_column='topic_ste_theta7_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta7_stock_t13', from_loa='country_month', from_column='topic_ste_theta7_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta8_stock_t1', from_loa='country_month', from_column='topic_ste_theta8_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta8_stock_t2', from_loa='country_month', from_column='topic_ste_theta8_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta8_stock_t13', from_loa='country_month', from_column='topic_ste_theta8_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta9_stock_t1', from_loa='country_month', from_column='topic_ste_theta9_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta9_stock_t2', from_loa='country_month', from_column='topic_ste_theta9_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta9_stock_t13', from_loa='country_month', from_column='topic_ste_theta9_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta10_stock_t1', from_loa='country_month', from_column='topic_ste_theta10_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta10_stock_t2', from_loa='country_month', from_column='topic_ste_theta10_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta10_stock_t13', from_loa='country_month', from_column='topic_ste_theta10_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta11_stock_t1', from_loa='country_month', from_column='topic_ste_theta11_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta11_stock_t2', from_loa='country_month', from_column='topic_ste_theta11_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta11_stock_t13', from_loa='country_month', from_column='topic_ste_theta11_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta12_stock_t1', from_loa='country_month', from_column='topic_ste_theta12_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta12_stock_t2', from_loa='country_month', from_column='topic_ste_theta12_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta12_stock_t13', from_loa='country_month', from_column='topic_ste_theta12_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta13_stock_t1', from_loa='country_month', from_column='topic_ste_theta13_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta13_stock_t2', from_loa='country_month', from_column='topic_ste_theta13_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta13_stock_t13', from_loa='country_month', from_column='topic_ste_theta13_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta14_stock_t1', from_loa='country_month', from_column='topic_ste_theta14_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(1)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta14_stock_t2', from_loa='country_month', from_column='topic_ste_theta14_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(2)
        .transform.missing.fill()
        )

    .with_column(Column('topic_ste_theta14_stock_t13', from_loa='country_month', from_column='topic_ste_theta14_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        )

    .with_column(Column('splag_wdi_sl_tlf_totl_fe_zs', from_loa='country_year', from_column='wdi_sl_tlf_totl_fe_zs')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('splag_wdi_sm_pop_refg_or', from_loa='country_year', from_column='wdi_sm_pop_refg_or')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('splag_wdi_sm_pop_netm', from_loa='country_year', from_column='wdi_sm_pop_netm')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('splag_wdi_ag_lnd_frst_k2', from_loa='country_year', from_column='wdi_ag_lnd_frst_k2')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('splag_vdem_v2x_libdem', from_loa='country_year', from_column='vdem_v2x_libdem')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('splag_vdem_v2xcl_dmove', from_loa='country_year', from_column='vdem_v2xcl_dmove')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('splag_vdem_v2x_accountability', from_loa='country_year', from_column='vdem_v2x_accountability')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('splag_vdem_v2xpe_exlsocgr', from_loa='country_year', from_column='vdem_v2xpe_exlsocgr')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('splag_vdem_v2xcl_rol', from_loa='country_year', from_column='vdem_v2xcl_rol')
        .transform.missing.fill()
        .transform.temporal.tlag(12)
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('agr_withdrawal_pct_t48', from_loa='country_year', from_column='agr_withdrawal_pct')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(48)
        .transform.missing.fill()
        )

    .with_column(Column('dam_cap_pcap_t48', from_loa='country_year', from_column='dam_cap_pcap')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(48)
        .transform.missing.fill()
        )

    .with_column(Column('groundwater_export_t48', from_loa='country_year', from_column='groundwater_export')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(48)
        .transform.missing.fill()
        )

    .with_column(Column('fresh_withdrawal_pct_t48', from_loa='country_year', from_column='fresh_withdrawal_pct')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(48)
        .transform.missing.fill()
        )

    .with_column(Column('ind_efficiency_t48', from_loa='country_year', from_column='ind_efficiency')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(48)
        .transform.missing.fill()
        )

    .with_column(Column('irr_agr_efficiency_t48', from_loa='country_year', from_column='irr_agr_efficiency')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(48)
        .transform.missing.fill()
        )

    .with_column(Column('services_efficiency_t48', from_loa='country_year', from_column='services_efficiency')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(48)
        .transform.missing.fill()
        )

    .with_column(Column('general_efficiency_t48', from_loa='country_year', from_column='general_efficiency')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(48)
        .transform.missing.fill()
        )

    .with_column(Column('water_stress_t48', from_loa='country_year', from_column='water_stress')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(48)
        .transform.missing.fill()
        )

    .with_column(Column('renewable_internal_pcap_t48', from_loa='country_year', from_column='renewable_internal_pcap')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(48)
        .transform.missing.fill()
        )

    .with_column(Column('renewable_pcap_t48', from_loa='country_year', from_column='renewable_pcap')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(48)
        .transform.missing.fill()
        )

    .with_column(Column('decay_ged_sb_5', from_loa='country_month', from_column='ged_sb_best_sum_nokgi')
        .transform.missing.replace_na()
        .transform.bool.gte(5)
        .transform.temporal.time_since()
        .transform.temporal.decay(24)
        .transform.missing.replace_na()
        )

    .with_column(Column('decay_ged_os_5', from_loa='country_month', from_column='ged_os_best_sum_nokgi')
        .transform.missing.replace_na()
        .transform.bool.gte(5)
        .transform.temporal.time_since()
        .transform.temporal.decay(24)
        .transform.missing.replace_na()
        )

    .with_column(Column('decay_ged_sb_100', from_loa='country_month', from_column='ged_sb_best_sum_nokgi')
        .transform.missing.replace_na()
        .transform.bool.gte(100)
        .transform.temporal.time_since()
        .transform.temporal.decay(24)
        .transform.missing.replace_na()
        )

    .with_column(Column('decay_ged_sb_500', from_loa='country_month', from_column='ged_sb_best_sum_nokgi')
        .transform.missing.replace_na()
        .transform.bool.gte(500)
        .transform.temporal.time_since()
        .transform.temporal.decay(24)
        .transform.missing.replace_na()
        )

    .with_column(Column('decay_ged_os_100', from_loa='country_month', from_column='ged_os_best_sum_nokgi')
        .transform.missing.replace_na()
        .transform.bool.gte(100)
        .transform.temporal.time_since()
        .transform.temporal.decay(24)
        .transform.missing.replace_na()
        )

    .with_column(Column('decay_ged_ns_5', from_loa='country_month', from_column='ged_ns_best_sum_nokgi')
        .transform.missing.replace_na()
        .transform.bool.gte(5)
        .transform.temporal.time_since()
        .transform.temporal.decay(24)
        .transform.missing.replace_na()
        )

    .with_column(Column('decay_ged_ns_100', from_loa='country_month', from_column='ged_ns_best_sum_nokgi')
        .transform.missing.replace_na()
        .transform.bool.gte(100)
        .transform.temporal.time_since()
        .transform.temporal.decay(24)
        .transform.missing.replace_na()
        )

    .with_column(Column('decay_acled_sb_5', from_loa='country_month', from_column='acled_sb_fat')
        .transform.missing.replace_na()
        .transform.bool.gte(5)
        .transform.temporal.time_since()
        .transform.temporal.decay(24)
        .transform.missing.replace_na()
        )

    .with_column(Column('decay_acled_os_5', from_loa='country_month', from_column='acled_os_fat')
        .transform.missing.replace_na()
        .transform.bool.gte(5)
        .transform.temporal.time_since()
        .transform.temporal.decay(24)
        .transform.missing.replace_na()
        )

    .with_column(Column('decay_acled_ns_5', from_loa='country_month', from_column='acled_ns_fat')
        .transform.missing.replace_na()
        .transform.bool.gte(5)
        .transform.temporal.time_since()
        .transform.temporal.decay(24)
        .transform.missing.replace_na()
        )

    .with_column(Column('splag_1_decay_ged_sb_5', from_loa='country_month', from_column='ged_sb_best_sum_nokgi')
        .transform.missing.replace_na()
        .transform.bool.gte(5)
        .transform.temporal.time_since()
        .transform.temporal.decay(24)
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('splag_1_decay_ged_os_5', from_loa='country_month', from_column='ged_os_best_sum_nokgi')
        .transform.missing.replace_na()
        .transform.bool.gte(5)
        .transform.temporal.time_since()
        .transform.temporal.decay(24)
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('splag_1_decay_ged_ns_5', from_loa='country_month', from_column='ged_ns_best_sum_nokgi')
        .transform.missing.replace_na()
        .transform.bool.gte(5)
        .transform.temporal.time_since()
        .transform.temporal.decay(24)
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('topic_tokens_t1_splag', from_loa='country_month', from_column='topic_tokens')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('topic_ste_theta0_stock_t1_splag', from_loa='country_month', from_column='topic_ste_theta0_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('topic_ste_theta1_stock_t1_splag', from_loa='country_month', from_column='topic_ste_theta1_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('topic_ste_theta2_stock_t1_splag', from_loa='country_month', from_column='topic_ste_theta2_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('topic_ste_theta3_stock_t1_splag', from_loa='country_month', from_column='topic_ste_theta3_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('topic_ste_theta4_stock_t1_splag', from_loa='country_month', from_column='topic_ste_theta4_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('topic_ste_theta5_stock_t1_splag', from_loa='country_month', from_column='topic_ste_theta5_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('topic_ste_theta6_stock_t1_splag', from_loa='country_month', from_column='topic_ste_theta6_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('topic_ste_theta7_stock_t1_splag', from_loa='country_month', from_column='topic_ste_theta7_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('topic_ste_theta8_stock_t1_splag', from_loa='country_month', from_column='topic_ste_theta8_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('topic_ste_theta9_stock_t1_splag', from_loa='country_month', from_column='topic_ste_theta9_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('topic_ste_theta10_stock_t1_splag', from_loa='country_month', from_column='topic_ste_theta10_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('topic_ste_theta11_stock_t1_splag', from_loa='country_month', from_column='topic_ste_theta11_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('topic_ste_theta12_stock_t1_splag', from_loa='country_month', from_column='topic_ste_theta12_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('topic_ste_theta13_stock_t1_splag', from_loa='country_month', from_column='topic_ste_theta13_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_column(Column('topic_ste_theta14_stock_t1_splag', from_loa='country_month', from_column='topic_ste_theta14_stock')
        .transform.missing.fill()
        .transform.missing.replace_na()
        .transform.temporal.tlag(13)
        .transform.missing.fill()
        .transform.spatial.countrylag(1,1,0,0)
        .transform.missing.replace_na()
        )

    .with_theme('fatalities002')
    .describe("""Predicting ln(fatalities), cm level
    
                             Queryset with all features
    
                             """)
    )

    return queryset_base
