from viewser import Queryset, Column

def generate():

    qs_conflict_history = (Queryset('fatalities002_pgm_conflict_history','priogrid_month')
                           
                        .with_column(Column('ln_ged_sb_dep', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_sb_decay_12_time_since', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.temporal.decay(12)
                            .transform.bool.gte(1)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_sb_splag_1', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.spatial.lag(1,1,0,0)
                            .transform.ops.ln()
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_ns_decay_12_time_since', from_loa='priogrid_month', from_column='ged_ns_best_count_nokgi')
                            .transform.temporal.decay(12)
                            .transform.bool.gte(1)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_os_decay_12_time_since', from_loa='priogrid_month', from_column='ged_os_best_count_nokgi')
                            .transform.temporal.decay(12)
                            .transform.bool.gte(1)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_ns_splag_1', from_loa='priogrid_month', from_column='ged_ns_best_count_nokgi')
                            .transform.spatial.lag(1,1,0,0)
                            .transform.ops.ln()
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_os_splag_1', from_loa='priogrid_month', from_column='ged_os_best_count_nokgi')
                            .transform.spatial.lag(1,1,0,0)
                            .transform.ops.ln()
                            .transform.missing.fill()
                            )

                        .with_column(Column('mov_avg_6_ged_best_sb', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.moving_average(6)
                            )

                        .with_column(Column('mov_avg_12_ged_best_sb', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.moving_average(12)
                            )

                        .with_column(Column('mov_avg_36_ged_best_sb', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.moving_average(36)
                            )

                        .with_column(Column('mov_sum_6_ged_best_sb', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.moving_sum(6)
                            )

                        .with_column(Column('mov_sum_12_ged_best_sb', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.moving_sum(12)
                            )

                        .with_column(Column('mov_sum_36_ged_best_sb', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.moving_sum(36)
                            )

                        .with_column(Column('ln_ged_sb_tlag_1', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_sb_tlag_2', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(2)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_sb_tlag_3', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(3)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_sb_tlag_4', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(4)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_sb_tlag_5', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(5)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_sb_tlag_6', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(6)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_sb_tlag_7', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(7)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_sb_tlag_8', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(8)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_sb_tlag_9', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(9)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_sb_tlag_10', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(10)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_sb_tlag_11', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(11)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_sb_tlag_12', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(12)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_ns_tlag_1', from_loa='priogrid_month', from_column='ged_ns_best_count_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_os_tlag_1', from_loa='priogrid_month', from_column='ged_os_best_count_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_sb_tlag_1_splag_1', from_loa='priogrid_month', from_column='ged_sb_best_sum_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.spatial.lag(1,1,0,0)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_ns_tlag_1_splag_1', from_loa='priogrid_month', from_column='ged_ns_best_count_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.spatial.lag(1,1,0,0)
                            .transform.missing.fill()
                            )

                        .with_column(Column('ln_ged_os_tlag_1_splag_1', from_loa='priogrid_month', from_column='ged_os_best_count_nokgi')
                            .transform.ops.ln()
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.spatial.lag(1,1,0,0)
                            .transform.missing.fill()
                            )

                        .with_theme('fatalities')
                        .describe("""Fatalities conflict history

                                                Predicting ln(fatalities) using conflict predictors

                                                """)
                        )
    
    return qs_conflict_history