name: Require Branch to Be Up-to-Date with Main

# Trigger this workflow on pull request events targeting a specific branch.
on:
  pull_request:
    branches:
      - main
      - test-protect-main-merge # for testing
  workflow_dispatch: # enables manual triggering

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
    
      - name: Fetch main branch
        run: |
          git fetch origin main
          git status

      - name: Print commit hashes
        run: |
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Current head: $(git rev-parse HEAD)"
          echo "Main: $(git rev-parse origin/main)"
          BASE=$(git merge-base HEAD origin/main)
          echo "Merge base: $BASE"


      - name: Compare branch with main
        run: |
          if ! git merge-base --is-ancestor origin/main HEAD; then
            echo "Branch is behind main. Aborting."
            exit 1
          else
            echo "Branch is up-to-date with main."
          fi

 