name: run generate_links_to_querysets.py on dispatch event

# Listen for the dispatch event from viewsforecasting
on:
  repository_dispatch:
    types: [trigger-generate_links_to_querysets]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout views_pipeline
      uses: actions/checkout@v3  

    - name: Set up Python  
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python script  
      run: |
        python documentation/catalogs/generate_links_to_querysets.py  
